[".config/nvim"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/refs/heads/v2.0.zip"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/wezterm/colors/everforest"]
    type = "archive"
    url = "https://github.com/frdwin/everforest-for-wezterm/archive/refs/heads/main.zip"
    refreshPeriod = "168h"
    stripComponents = 1