[".config/nvim"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/refs/heads/v2.0.tar.gz"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/wezterm/colors/everforest"]
    type = "archive"
    url = "https://github.com/frdwin/everforest-for-wezterm/archive/refs/heads/main.tar.gz"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/bat/themes/everforest"]
    type = "archive"
    url = "https://github.com/mhanberg/everforest-textmate/archive/refs/heads/main.tar.gz"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/helix/runtime"]
  type = "archive"
  url = "https://github.com/helix-editor/helix/archive/refs/heads/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["helix-master/runtime/**"]
