---
- hosts: all
  connection: local
  vars:
    username: "{% if ansible_distribution == 'MacOSX' %}{{ mac_username }}{% else %}{{ nix_username }}{% endif %}"
    user_home: "{% if ansible_distribution == 'MacOSX' %}{{ mac_user_home }}{% else %}{{ nix_user_home }}{% endif %}"
    dotfiles_home: "{% if ansible_distribution == 'MacOSX' %}{{ mac_user_home }}/.dotfiles{% else %}{{ nix_user_home }}/.dotfiles{% endif %}"

  pre_tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: 'You must update Ansible to at least 2.7 to use this playbook.'

  tasks:
    - include: tasks/packages.yml
      tags: packages

    - include: tasks/dotfiles.yml
      tags: dotfiles

    - include: tasks/gui.yml
      tags: gui

    - include: tasks/shell.yml
      tags: shell

# Modified from https://github.com/davestephens/ansible-dotfiles
