---
- hosts: all
  connection: local

  pre_tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full | version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this playbook."

  tasks:
    - include: tasks/packages.yml
      tags: packages

    - include: tasks/dotfiles.yml
      tags: dotfiles

    - include: tasks/shell.yml
      tags: shell

# Modified from https://github.com/davestephens/ansible-dotfiles