#!/bin/sh

# test for an existing bus daemon, just to be safe
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
  # if not found, launch a new one
  eval "$(dbus-launch --sh-syntax --exit-with-session)"
  echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

# set env vars
export SXHKD_SHELL=/bin/bash
# export VDPAU_DRIVER=radeonsi
# export LIBVA_DRIVER_NAME=i965

# fix monitors
xrandr --dpi 100
xrandr --output DisplayPort-0 --auto
xrandr --output DP3 --auto
xrandr --output DVI-I-0 --auto
xrandr --output DVI-I-0 --right-of DisplayPort-0
xrandr --output DP3 --left-of DisplayPort-0

# fix cursor
xsetroot -cursor_name left_ptr

# enable fonts
xset +fp /Users/chadvanw/.local/share/fonts/
xset fp rehash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# exec
shxkd &
exec dbus-launch bspwm
