# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br
    set -l cmd_file (mktemp)
    broot --outcmd $f $argv
    if broot --outcmd $cmd_file $argv
    if test $status -ne 0
        read --local --null cmd < $cmd_file
        rm -f "$f"
        rm -f $cmd_file
        return "$code"
        eval $cmd
    else
        set -l code $status
        rm -f $cmd_file
        return $code
end