#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "{{ mono_font }}:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff{{ background }}
yabai -m config status_bar_foreground_color  0xff{{ foreground }}
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xff{{ blue }}
yabai -m config normal_window_border_color   0xff{{ black }}
yabai -m config insert_window_border_color   0xff{{ green }}
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Cisco AnyConnect*" manage=off

# Work Items
yabai -m rule --add app="^Firefox Developer Edition$" space=1
yabai -m rule --add app="^IntelliJ IDEA$" space=2
yabai -m rule --add app="^PyCharm$" space=2
yabai -m rule --add app="^Code$" space=5

# Personal Items
yabai -m rule --add app="^Firefox Nightly$" space=6
yabai -m rule --add app="^Telegram$" space=7
yabai -m rule --add app="^Signal$" space=7
yabai -m rule --add app="^Amazon Chime$" space=8
yabai -m rule --add app="^Outlook$" space=9
yabai -m rule --add app="^Spotify$" space=10

echo "yabai configuration loaded.."