---
linked_dotfiles:
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .gitignore
  - .xinitrc
linked_config_folders:
  - nvim
  - fish
  - alacritty
  - gtk-3.0
  - bspwm
  - sxhkd
  - polybar
  - dunst
executable_dotfiles:
  - bspwm/bspwmrc
  - .xinitrc