apt_packages:
  - ansible
  - curl
  - wget
  - git
  - git-lfs
  - git-extras
  - htop
  - jq
  - nmap
  - sl
  - zip
  - tree
  - neofetch
  - rsync
  - unrar
  - p7zip-full
  - p7zip-rar
  - vim
  - neovim
  - fish
  - nodejs
  - yarn
  - python
  - python-pip
  - python3
  - python3-pip
  - unzip
  - openjdk-8-jdk-headless
  - openjdk-8-source
  - openjdk-8-doc
  - openjdk-11-jdk-headless
  - openjdk-11-source
  - openjdk-11-doc
  - dbus-x11
  - docker-ce
  - tmux
  - figlet
  - net-tools
  - flatpak
  - ranger
  - ruby

apt_packages_to_remove:
  - docker.io

# pyenv_packages:
#   - make
#   - libbz2-dev
#   - libreadline-dev
#   - libsqlite3-dev
#   - llvm
#   - libncursesw5-dev
#   - xz-utils
#   - tk-dev

apt_signing_keys:
  - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  - https://dl.yarnpkg.com/debian/pubkey.gpg
  - https://download.docker.com/linux/ubuntu/gpg
  - https://packages.microsoft.com/keys/microsoft.asc
  - https://updates.signal.org/desktop/apt/keys.asc
  - https://insomnia.rest/keys/debian-public.key.asc

ubuntu_keyserver_keys:
  - 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367 # ansible
  - E1DD270288B4E6030699E45FA1715D88E1DF1F24 # git core
  - 59FDA1CE1B84B3FAD89366C027557F056DC33CA5 # fish shell
  - 9DBB0BE9366964F134855E2255F96FCF8231B6DD # neovim
  - 3653E21064B19D134466702E43D5C49532CBA1A9 # yubikey

apt_repositories:
  - 'deb https://deb.nodesource.com/node_8.x cosmic main'
  - 'deb https://dl.yarnpkg.com/debian/ stable main'
  - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_distribution }} stable'
  - 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
  - 'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main'
  - 'deb https://dl.bintray.com/getinsomnia/Insomnia /'

ppa_repositories:
  - 'ppa:ansible/ansible'
  - 'ppa:git-core/ppa'
  - 'ppa:fish-shell/release-3'
  - 'ppa:neovim-ppa/stable'
  - 'ppa:yubico/stable'
  - 'ppa:alexlarsson/flatpak'

ruby_gems:
  - lolcat

user_pip2_packages:
  - neovim
  - wakatime

user_pip3_packages:
  - awscli
  - neovim
  - pydf
  - pipenv
  - awslogs
  - httpie
  - cfn-lint
  - yamllint

global_npm_packages:
  - neovim
  - npm-check-updates
  - serverless
  - npx
  - prettier
  - lerna
  - '@vue/cli'
  - tldr
  - gatsby-cli
  - jest
  - aws-cdk
  - npm
  - colortest

terraform_version: 0.11.7
terragrunt_version: 0.14.11
awsvault_version: 4.5.1

debs:
  - https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb
  - https://github.com/cjbassi/gotop/releases/download/3.0.0/gotop_3.0.0_linux_amd64.deb

# stuff that just needs unpacking
# archives_to_unpack:
#   - https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.14.5037.tar.gz

# random stuff in zips/tars/gz etc
non_standard_packages:
  - name: terraform
    url: 'https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip'
    version: 0.11.7

straight_downloads:
  - name: terragrunt
    url: 'https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64'
    dir: '/home/{{ username }}/programs/terragrunt-{{ terragrunt_version }}'
  - name: 'aws-vault'
    url: 'https://github.com/99designs/aws-vault/releases/download/v{{ awsvault_version }}/aws-vault-linux-amd64'
    dir: '/home/{{ username }}/programs/aws-vault-{{ awsvault_version }}'

# stuff in rar packages (seriously?!)
# rar_packages:
#   - name: netrunner
#     url: http://www.mysticbbs.com/downloads/nr20b186.rar
#     version: 2.0b186

# nvm_install_script: https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh
