modelRoles: 
  smol: amazon-bedrock/global.anthropic.claude-sonnet-4-6
  plan: amazon-bedrock/global.anthropic.claude-opus-4-6-v1:high
  commit: amazon-bedrock/eu.anthropic.claude-haiku-4-5-20251001-v1:0
  default: amazon-bedrock/global.anthropic.claude-opus-4-6-v1
  slow: amazon-bedrock/global.anthropic.claude-opus-4-6-v1:xhigh
  task: amazon-bedrock/global.anthropic.claude-sonnet-4-6
theme: 
  dark: kanagawa-wave
symbolPreset: unicode
browser: 
  enabled: false
  headless: false
async: 
  enabled: true
disabledExtensions: 
  []
disabledProviders: 
  - claude
  - codex
  - gemini
  - github-copilot
lastChangelogVersion: 13.3.6
compaction: 
  enabled: true
  thresholdPercent: 80
  strategy: context-full
  handoffSaveToDisk: true
secrets: 
  enabled: true
providers: 
  webSearch: kagi
hideThinkingBlock: true
steeringMode: all
memories: 
  enabled: true
treeFilterMode: default
ask: 
  timeout: 0
renderMermaid: 
  enabled: true
notebook: 
  enabled: false
checkpoint: 
  enabled: true
calc: 
  enabled: true
task: 
  eager: true
commands: 
  enableClaudeUser: false
  enableClaudeProject: false
python: 
  toolMode: both
bashInterceptor: 
  enabled: true
  simpleLs: true
interruptMode: immediate
statusLine:
  separator: slash
display:
  showTokenUsage: false
