#! /bin/sh

#                     ___           ___           ___         ___     
#      _____         /  /\         /__/\         /  /\       /__/\    
#     /  /::\       /  /:/_       _\_ \:\       /  /::\     |  |::\   
#    /  /:/\:\     /  /:/ /\     /__/\ \:\     /  /:/\:\    |  |:|:\  
#   /  /:/~/::\   /  /:/ /::\   _\_ \:\ \:\   /  /:/~/:/  __|__|:|\:\ 
#  /__/:/ /:/\:| /__/:/ /:/\:\ /__/\ \:\ \:\ /__/:/ /:/  /__/::::| \:\
#  \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\ \:\/:/ \  \:\/:/   \  \:\~~\__\/
#   \  \::/ /:/   \  \::/ /:/   \  \:\ \::/   \  \::/     \  \:\      
#    \  \:\/:/     \__\/ /:/     \  \:\/:/     \  \:\      \  \:\     
#     \  \::/        /__/:/       \  \::/       \  \:\      \  \:\    
#      \__\/         \__\/         \__\/         \__\/       \__\/  

export _JAVA_AWT_WM_NONREPARENTING=1

# Kill all running applications before starting
killall -9 sxhkd dunst polybar compton

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

sxhkd &
polybar --reload left &
polybar --reload center &
polybar --reload right &
dunst &
compton &
betterlockscreen -u /home/{{ username }}/images/background.png &
xautolock -locker 'betterlockscreen --lock blur' -time 5 -notify 25 -corners ---- -cornerdelay 10 -cornersize 20 -notifier "notify-send 'Locking in 25 seconds.'" &

feh --bg-fill /home/{{ username }}/images/background.png

# left
bspc monitor {{ left_monitor }} -d 1 2 3
# center
bspc monitor {{ center_monitor }} -d 4 5 6
# right
bspc monitor {{ right_monitor }} -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color '#{{ brblue }}'
bspc config normal_border_color '#{{ brblack }}'
bspc config focused_border_color '#{{ brgreen }}'

bspc rule -a jetbrains-toolbox state=floating
bspc rule -a 'Yubico Authenticator' state=floating
bpsc rule -a Firefox:* desktop='^1'
bspc rule -a Slack:* desktop='^2'
bspc rule -a Sginal:* desktop='^3'
bspc rule -a Spotify:* desktop='^3'
bspc rule -a TelegramDesktop:* desktop='^3'
