["runtime"]
  type = "archive"
  url = "https://github.com/helix-editor/helix/archive/refs/heads/master.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["helix-master/runtime/**"]
