[language-server.ucm]
command = "ncat"
args = ["localhost", "5757"]

[[language]]
name = "unison"
language-servers = [ "ucm" ]

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true
formatter = { command = "mise", args = ["exec", "pipx:black", "--", "black", "--line-length", "140", "--quiet", "-"] }

[language-server.pyright]
command = "mise"
args = ["exec", "npm:pyright", "--", "pyright-langserver", "--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "mise"
args = ["exec", "ruff", "--", "ruff", "server"]

[language-server.ruff.config.settings]
lineLength = 140

[language-server.ruff.config.settings.lint]
ignore = ["E501"]

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[[language]]
# Brazil Config files
name = "perl"
scope = "source.brazil-config"
file-types = [{glob = "Config"}]
roots = ["Config"]
comment-token = "#"
language-servers = ["barium"]
grammar = "perl"

[language-server.barium]
command = "barium"
